name: push-to-gitee

on: [push]

jobs:
  sync:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Init git
      env:
        GITEE_PRIVATE: ${{ secrets.GITEE_PRIVATE }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GITEE_PRIVATE" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
        git config --global user.email "smczx@hotmail.com"
        git config --global user.name "ControlNet"

    - name: Clone from gitee
      run: git clone git@gitee.com:controlnet/wt-data-project.data.git

    - name: Update the files
      run: |
        cp -r joined wt-data-project.data/joined
        cp -r ts wt-data-project.data/ts
        cp -r wk wt-data-project.data/wk
        cp ab_ranks_0.csv wt-data-project.data
        cp ab_ranks_1.csv wt-data-project.data
        cp ab_ranks_all.csv wt-data-project.data
        cp rb_ranks_0.csv wt-data-project.data
        cp rb_ranks_1.csv wt-data-project.data
        cp rb_ranks_all.csv wt-data-project.data
        cp sb_ranks_0.csv wt-data-project.data
        cp sb_ranks_1.csv wt-data-project.data
        cp sb_ranks_all.csv wt-data-project.data
        cp README.md wt-data-project.data
        cp LICENSE wt-data-project.data
        cp .gitignore wt-data-project.data

    - name: Commit and Push
      run: |
        cd wt-data-project.data
        git add -A
        git commit -m "update"
        git push origin HEAD:master --force
